on: [push]

name: Obtain version from Reliza and push helm chart if there were changes

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Obtain version and stream version to Reliza Hub
        run: |
          docker pull relizaio/reliza-cli
          
          # get latest completed release to see if there are diffs in helm chart
          do_helm_release="true"
          last_commit=$(docker run --rm relizaio/reliza-cli getlatestrelease -i ${{ secrets.RELIZA_API_ID }} -k ${{ secrets.RELIZA_API_KEY }} \
            --branch $GITHUB_REF | jq -r ".sourceCodeEntryDetails.commit")
          if [ ! -z "$last_commit" ]
          then
            # check if there were changes on helm chart since last release
            changes=$(git log $last_commit..$GITHUB_SHA helm/ | wc -l)
            if [ $changes -eq 0 ]; then do_helm_release="false"; fi
          fi
          
          echo "do helm release = $do_helm_release"
          
          if [ "true" == "$do_helm_release" ]
          then
            # get version
          
            docker run --rm relizaio/reliza-cli getversion -k ${{ secrets.RELIZA_API_KEY }} -i ${{ secrets.RELIZA_API_ID }} -b $GITHUB_REF > full_version_output 2>&1
            cat full_version_output | jq -r ".version" > version
            vvar=$(cat version)
            
            # update version on the chart
            sed -i "/version: /s/.*/version: $vvar/" helm/Chart.yaml
            
            # git commit and update
            git config --global user.name 'reliza-auto'
            git config --global user.email 'info@reliza.io'
            git add .
            git commit -m "chore: bump mafia helm chart version to $vvar"
            git push
            commit_sha=$(git log -1 --pretty='%H')
            
            if [ ! -z "$last_commit" ]
            then
              commit_list=$(git log $last_commit..$commit_sha --date=iso-strict --pretty='%H|||%ad|||%s' | base64 -w 0)
            else
              commit_list=$(git log -2 --date=iso-strict --pretty='%H|||%ad|||%s' | base64 -w 0)
            fi
              
            
            # publish helm chart on Reliza Hub registry
            docker run --rm -v $(pwd)/helm:/apps/helm relizaio/helmpush push /apps/helm ${{ secrets.HELM_CHART_REPO }} -u '${{ secrets.HELM_PUSH_LOGIN }}' -p '${{ secrets.HELM_PUSH_TOKEN }}'
            
            # compute sha256 digest for helm chart package tgz
            sha_digest=$(docker run --rm -v $(pwd)/helm:/apps/helm --entrypoint /bin/sh relizaio/helmpush -c "helm package helm/ > /dev/null && sha256sum *.tgz | cut -f 1 -d ' '")
            
            # submit build data to Reliza Hub
            docker run --rm relizaio/reliza-cli addrelease -b $GITHUB_REF --commits $commit_list -v $vvar \
              -i ${{ secrets.RELIZA_API_ID }} -k ${{ secrets.RELIZA_API_KEY }} --artid ${{ secrets.HELM_CHART_REPO }}mafia \
              --artbuildid github$GITHUB_ACTION$GITHUB_SHA --artcimeta GitHub Actions --arttype File --artdigests sha256:$sha_digest
          fi

